mysql:
- name: "default"
  username: "root"
  password: "123456"
  database: "db_ginadmin"
  host: "127.0.0.1"
  port: 3306
  max_open_conn: 50
  max_idle_conn: 20
redis:
  addr: "localhost:6379"
  db: 0
  password: ""
session:
  session_name: "gosession_id"
base:
  host: 0.0.0.0
  port: 20011
  log_media: "redis"