mysql:
  username: "root"
  password: "123456"
  database: "db_beego"
  host: "127.0.0.1"
  port: 3306
  max_open_conn: 50
  max_idle_conn: 20
redis:
  addr: "127.0.0.1:6380"
  db: 0
  password: "zxcde@1"
session:
  session_name: "gosession_id"
base:
  host: 0.0.0.0
  port: 20011
  fill_data: true
  migrate_table: true
  log_media: "redis"